// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyADAKA9OKy7QgmSuMcvJn5Q7hWT5QCfeB4',
    appId: '1:434874035165:web:ea791a15656c32d2022434',
    messagingSenderId: '434874035165',
    projectId: 'hostel-hub69',
    authDomain: 'hostel-hub69.firebaseapp.com',
    storageBucket: 'hostel-hub69.appspot.com',
    measurementId: 'G-JX1H8B9BYQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCbjepohvOGPaSZ4nhDrsaUAZZnufwwdQE',
    appId: '1:434874035165:android:680983b568734d49022434',
    messagingSenderId: '434874035165',
    projectId: 'hostel-hub69',
    storageBucket: 'hostel-hub69.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyACKded3qhFqXkjxugorCgxlUthVWhqCQI',
    appId: '1:434874035165:ios:3e33e364fb029ceb022434',
    messagingSenderId: '434874035165',
    projectId: 'hostel-hub69',
    storageBucket: 'hostel-hub69.appspot.com',
    iosClientId: '434874035165-t4cnq32nufn0ujcmr1m03pjndubc9k91.apps.googleusercontent.com',
    iosBundleId: 'com.example.dbProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyACKded3qhFqXkjxugorCgxlUthVWhqCQI',
    appId: '1:434874035165:ios:3e33e364fb029ceb022434',
    messagingSenderId: '434874035165',
    projectId: 'hostel-hub69',
    storageBucket: 'hostel-hub69.appspot.com',
    iosClientId: '434874035165-t4cnq32nufn0ujcmr1m03pjndubc9k91.apps.googleusercontent.com',
    iosBundleId: 'com.example.dbProject',
  );
}
