// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAFJ0Lcx9zjTc0lhNPKiYIkzLCXfeLMmCU',
    appId: '1:887594861542:web:f734ce1ca1af6d088d0c27',
    messagingSenderId: '887594861542',
    projectId: 'flutter-login-8fd44',
    authDomain: 'flutter-login-8fd44.firebaseapp.com',
    databaseURL: 'https://flutter-login-8fd44-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-login-8fd44.appspot.com',
    measurementId: 'G-FMVWKN5XJZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB0-1_CDEhzF-KJmWBJzDLVOxGw-V6AvP4',
    appId: '1:887594861542:android:6719e6af31ffe6688d0c27',
    messagingSenderId: '887594861542',
    projectId: 'flutter-login-8fd44',
    databaseURL: 'https://flutter-login-8fd44-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-login-8fd44.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD5dEYsbBE_3bdh4SLe1IF-4z-iP7ZOEoA',
    appId: '1:887594861542:ios:a37b33908dd023118d0c27',
    messagingSenderId: '887594861542',
    projectId: 'flutter-login-8fd44',
    databaseURL: 'https://flutter-login-8fd44-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-login-8fd44.appspot.com',
    iosClientId: '887594861542-mj7lu6abhde60iiaq39cv8si7ja0l2ns.apps.googleusercontent.com',
    iosBundleId: 'com.example.dbProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD5dEYsbBE_3bdh4SLe1IF-4z-iP7ZOEoA',
    appId: '1:887594861542:ios:a37b33908dd023118d0c27',
    messagingSenderId: '887594861542',
    projectId: 'flutter-login-8fd44',
    databaseURL: 'https://flutter-login-8fd44-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-login-8fd44.appspot.com',
    iosClientId: '887594861542-mj7lu6abhde60iiaq39cv8si7ja0l2ns.apps.googleusercontent.com',
    iosBundleId: 'com.example.dbProject',
  );
}
